package uk.co.simon.nflbettracker;
import android.app.*;import android.os.*;import android.webkit.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class MainActivity extends Activity{
 private final Handler handler=new Handler(Looper.getMainLooper());private final ExecutorService worker=Executors.newSingleThreadExecutor();private WebView web;private boolean running;
 private static final String[] ESPN={"https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard","https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard"};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff07172e);getWindow().setNavigationBarColor(0xff07172e);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.setBackgroundColor(0xff07172e);web.addJavascriptInterface(new Bridge(),"Android");web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){refresh();}});web.loadUrl("file:///android_asset/index.html");setContentView(web);}
 @Override protected void onStart(){super.onStart();running=true;handler.post(cycle);}@Override protected void onStop(){running=false;handler.removeCallbacksAndMessages(null);super.onStop();}@Override protected void onDestroy(){worker.shutdownNow();web.destroy();super.onDestroy();}
 public class Bridge{@JavascriptInterface public void refresh(){MainActivity.this.refresh();}}
 private final Runnable cycle=new Runnable(){public void run(){if(!running)return;refresh();handler.postDelayed(this,30000);}};
 private void refresh(){worker.execute(()->{String error="No ESPN response";for(String url:ESPN)try{String json=get(url);web.post(()->web.evaluateJavascript("window.receiveESPN("+json+")",null));return;}catch(Exception e){error=e.getClass().getSimpleName()+": "+e.getMessage();}String safe=error.replace("\\","\\\\").replace("'","\\'");web.post(()->web.evaluateJavascript("window.syncError('"+safe+"')",null));});}
 private String get(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setUseCaches(false);c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36");c.setRequestProperty("Accept","application/json,text/plain,*/*");c.setRequestProperty("Accept-Encoding","identity");c.setRequestProperty("Referer","https://www.espn.com/");int code=c.getResponseCode();InputStream stream=code>=200&&code<300?c.getInputStream():c.getErrorStream();String body="";if(stream!=null)try(InputStream in=stream){body=new String(in.readAllBytes(),StandardCharsets.UTF_8);}c.disconnect();if(code<200||code>=300)throw new IOException("HTTP "+code);return body;}
}
